version: '3'
services:
  app:
    container_name: my_go_app
    build:
      context: .
      dockerfile: Dockerfile3
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/my_app
    environment:
      - PORT=8080
